### ISSUE TITLE
Database tables diagram 

### ISSUE THREAD

**Issue by Moamin-AbuEwaida** [HYF-Connect/hyf-connect#10]
Regarding this comment from Dirk about the database tables.
```
I think the SelectedSkill construction is a bit weird.
Was this to show the 'top 3 ?'
In that case I would delete the SelectedSkill table, 
remove FK flag in UserSkill and just keep the flag SelectedSkill as is.
```
 we used a separate table for selectedSkills -in orange- where we were pointing to the idea of the user can select 3 skills to be highlighted/shown at the users page per each user ticket rather than showing all the skills the user select while building the portfolio

as we understood from Dirk's comment, the user will write down the skills him/herself. Our idea that the user will be selecting the skills to be highlighted in the portfolio. In other words the user wont waste a lot of time of building the portfolio in the same time for us with the backend will be easier to do the connection to the frontend when it's a drop list rather than a input filed

what do you think??   

[the tables digram](https://app.diagrams.net/#G1OdO_4rFJiMc-CbcNdbnGfv_Oh6RcrD-x)

**Comment by yoshimalaise** [comment]
Hi @Moamin-AbuEwaida,

Your current model looks like a mix between two possible solutions that have been discussed.

One of your options could be to remove the SelectedSkill table,

And then instead change the SelectedSkill field In the UserSkill table to be a boolean instead of a foreign key. 
This flag can then be set to true if you want to list this skill in the user's top 3. This way the user can select which of his skills will be highlighted.

Alternatively if you want to allow the user to also specify the order in which the highlighted skills are shown you can change the boolean field to a number field and use (0 for not shown, 1 for shown on first place, 2 for shown on second place and 3 for shown third)

OR

a third option would be to remove the status flag from the UserSkill table and instead add 3 extra foreign key fields to the user table (e.g. firstSelected skill that points to the Userskill that should be shown first, secondSelectedSkill...)

All of these options have advantages and drawbacks, so think about it and try to decide which of the 3 options presented here you like the most and try to find a reason why you choose that solution. 

We are of course happy to discuss your findings.

Good luck!

**Comment by Moamin-AbuEwaida** [comment]
Thanks alot @yoshimalaise !! it's clear to me now 
we'll discuss this with the team then and pick one way and move forward with. Personally I'm with the 1st option that set the selectedSkill field as boolean :smiling_imp:
